import { createOrUpdateObjectWithKeySameAsValue } from '../../util/helper';

export default createOrUpdateObjectWithKeySameAsValue([
  'SHOW_RESUME_SECTION_FORM_MODAL',

  'SET_CURRENT_RESUME_SECTION_ITEM_ID',

  'GET_ALL_RESUME_SECTIONS',
  'GET_ALL_RESUME_SECTIONS_SUCCESS',
  'GET_ALL_RESUME_SECTIONS_ERROR',

  'CREATE_RESUME_SECTION',
  'CREATE_RESUME_SECTION_SUCCESS',
  'CREATE_RESUME_SECTION_ERROR',

  'UPDATE_RESUME_SECTION',
  'UPDATE_RESUME_SECTION_SUCCESS',
  'UPDATE_RESUME_SECTION_ERROR',

  'DELETE_RESUME_SECTION',
  'DELETE_RESUME_SECTION_SUCCESS',
  'DELETE_RESUME_SECTION_ERROR',


  'SHOW_XP_FORM_MODAL',
  'SET_CURRENT_XP_ITEM_ID',

  'CREATE_XP',
  'CREATE_XP_SUCCESS',
  'CREATE_XP_ERROR',

  'UPDATE_XP',
  'UPDATE_XP_SUCCESS',
  'UPDATE_XP_ERROR',

  'DELETE_XP',
  'DELETE_XP_SUCCESS',
  'DELETE_XP_ERROR',


  'SHOW_SKILL_FORM_MODAL',
  'SET_CURRENT_SKILL_ITEM_ID',

  'GET_ALL_SKILLS',
  'GET_ALL_SKILLS_SUCCESS',
  'GET_ALL_SKILLS_ERROR',

  'CREATE_SKILL',
  'CREATE_SKILL_SUCCESS',
  'CREATE_SKILL_ERROR',

  'UPDATE_SKILL',
  'UPDATE_SKILL_SUCCESS',
  'UPDATE_SKILL_ERROR',

  'DELETE_SKILL',
  'DELETE_SKILL_SUCCESS',
  'DELETE_SKILL_ERROR',
]);
