import { createOrUpdateObjectWithKeySameAsValue } from '../../util/helper';

export default createOrUpdateObjectWithKeySameAsValue([
  'SAVE_USER',
  'LOG_OUT',
  'LOAD_USER',
  'LOAD_USER_SUCCESS',
  'LOAD_USER_ERROR',

  'UPDATE_USER',
  'UPDATE_USER_SUCCESS',
  'UPDATE_USER_ERROR',

  'UPDATE_ACCOUNT',
  'UPDATE_ACCOUNT_SUCCESS',
  'UPDATE_ACCOUNT_ERROR',

  'UPDATE_PASSWORD',
  'UPDATE_PASSWORD_SUCCESS',
  'UPDATE_PASSWORD_ERROR',
  
  'SHOW_USER_BASIC_INFO_FORM_MODAL',
  'SHOW_USER_AVATAR_FORM_MODAL',
  'SHOW_USER_DETAIL_INFO_FORM_MODAL',
  
]);
